# Generated by Django 3.2.23 on 2023-11-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20231115_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
